"use client";

import React, { useEffect, useState } from "react";
import Prism from "prismjs"; // Import Prism.js
import "prismjs/components/prism-jsx";
import "../../prism-theme.css";
import useBrandStore from "@/store/useBrandStore";
import Code from "@/component/Code";

export const pageIndex = `import { Inter } from "next/font/google";
import "./globals.css";
import Topnav from "@/components/TopNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topnav />{children}</body>
    </html>
  );
}
`;

const hilight = (code, language = "markup") => {
  return Prism.highlight(code, Prism.languages[language], language);
};

const Page = () => {
  const brandId = useBrandStore((state) => state.brandId);
  const workspaceExist = useBrandStore((state) => state.workspaceExists);
  const language = "jsx";
  const paCode = hilight(pageIndex, language);

  const pageCodeSnippets = [
    { heading: "Script code", content: paCode, copyContent: pageIndex },
  ];

  return (
    <div>
      {/* Main content container */}
      <div className="ml-20 px-5 overflow-y-auto h-screen ">
        <h1 className="text-2xl font-bold py-5 sticky top-0 bg-[#000] border-b-2">
          Code snippets
        </h1>
        <div className="w-full h-[85%] gap-5 mt-8 flex  justify-center  no-scrollbar">
          <div className="w-[60%] h-full overflow-y-auto overflow-hidden bg-[#161616] rounded-[12px] p-6 no-scrollbar">
            <h2 className="text-white text-xl font-semibold mb-4">
              Copy the script and paste it into your main code — that's it! See
              the magic ✨
            </h2>

            <Code codes={pageCodeSnippets} />
          </div>

          <div className="w-[40%] h-[40%] bg-[#161616] rounded-xl overflow-hidden flex items-center justify-center">
            <iframe
              width="100%"
              height="100%"
              src="https://www.youtube.com/embed/rteD2vHPjaM"
              title="YouTube Video"
              frameBorder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowFullScreen
              className="rounded-xl"
            ></iframe>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Page;
