import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider } from "@/providers/tanstack-provider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Shoppie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackProvider>{children}</TanstackProvider>
        <Toaster />
      </body>
    </html>
  );
}
