import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider } from "@/providers/tanstack-provider";
import { ReactNode } from "react";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Shoppie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <TanstackProvider>
      {children}
      <Toaster />
    </TanstackProvider>
  );
}
